version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8

  pre_build:
    commands:
      # Updating packages on container, and checking home path and python version for logging purposes.
      - apt-get -qq update
      - echo $HOME
      - which python3

  build:
    commands:
    # Installing AWSCLI, AWS SAM CLI, PyTest, and Requests package
      - pip3 install awscli -qq
      - pip3 install pytest -qq
      - pip3 install pytest-cov -qq
      - pip3 install --target lambdas/process-modem-data/lambda-code requests

    # Executing SAM template
      - aws cloudformation package --template-file lambdas/samTemplate.yml --s3-bucket $S3_Bucket --output-template-file outputSamTemplate.yaml
      - ls -l lambdas/process-modem-data/lambda-code
      - python3 -B -m pytest -v lambdas/Lambda1/Tests/ --cov=.
      - python3 -B -m pytest -v lambdas/Lambda2/Tests/ --cov=.


artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml