AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Lambdas


Parameters:
  CDFURL:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: "CDFURL"
    Description: "CDF url for the lambda"

  CERTBKT:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: "CERTBKT"
    Description: "Name of the S3 bucket holding certs"

  LambdaRole:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: "LambdaRole"
    Description: "ARN for the default Lambda Role"


Resources:
  ProcessModemData:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: ProcessModemData
      Handler: ProcessModemData.lambda_handler
      Runtime: python3.8
      CodeUri: ./ProcessModemData/lambda-code
      Description: 'Store required Modem MQTT data in CDF'
      MemorySize: 128
      Timeout: 5
      Role: !Ref LambdaRole
      Environment:
        Variables:
          CDFURL: !Ref CDFURL

  CreateRTRADIOMsg:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: CreateRTRADIOMsg
      Handler: CreateRTRADIOMsg.lambda_handler
      Runtime: python3.8
      CodeUri: ./CreateRTRADIOMsg/lambda-code
      Description: 'Get data from CDF and construct RTRADIO message'
      MemorySize: 128
      Timeout: 5
      Role: !Ref LambdaRole
      Environment:
        Variables:
          CDFURL: !Ref CDFURL

  CreateJSON:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: CreateJSON
      Handler: CreateJSON.lambda_handler
      Runtime: python3.8
      CodeUri: ./CreateJSON/lambda-code
      Description: 'Create json from raw data'
      MemorySize: 128
      Timeout: 30
      Role: !Ref LambdaRole
      Environment:
        Variables:
          CDFURL: !Ref CDFURL
          CERTBKT: !Ref CERTBKT

  ConsumeCSV:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: ConsumeCSV
      Handler: ConsumeCSV.lambda_handler
      Runtime: python3.8
      CodeUri: ./ConsumeCSV/lambda-code
      Description: 'Load CSV file, read row, and pass contents out to Step Function'
      MemorySize: 128
      Timeout: 30
      Role: !Ref LambdaRole

  ConsumeCSVForDeleteCDF:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: ConsumeCSVForDeleteCDF
      Handler: ConsumeCSVForDeleteCDF.lambda_handler
      Runtime: python3.8
      CodeUri: ./ConsumeCSVForDeleteCDF/lambda-code
      Description: 'Read all entities in CSV to allow them to be removed from the system'
      MemorySize: 128
      Timeout: 30
      Role: !Ref LambdaRole

  PopulateCDF:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: PopulateCDF
      Handler: PopulateCDF.lambda_handler
      Runtime: python3.7
      CodeUri: ./PopulateCDF/lambda-code
      Description: 'Create cert(s) and CDF entity from json data'
      MemorySize: 128
      Timeout: 30
      Role: !Ref LambdaRole
      Environment:
        Variables:
          CDFURL: !Ref CDFURL
          CERTBKT: !Ref CERTBKT

  DeleteCDF:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: DeleteCDF
      Handler: DeleteCDF.lambda_handler
      Runtime: python3.7
      CodeUri: ./DeleteCDF/lambda-code
      Description: 'Remove specified entity from CDF'
      MemorySize: 128
      Timeout: 30
      Role: !Ref LambdaRole
      Environment:
        Variables:
          CDFURL: !Ref CDFURL
          CERTBKT: !Ref CERTBKT