AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Lambdas
Resources:

  ProcessModemData:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: Process-Modem-Data
      Handler: process-modem-data.lambda_handler
      Runtime: python3.8
      CodeUri: ./process-modem-data/lambda-code
      Description: 'Process-Modem-Data'
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          BASE_URL: https://cbzvks1j2d.execute-api.us-west-2.amazonaws.com/Stage

      #Role: 'arn:aws:iam::453698135753:role/service-role/InfraTest'
      #Not specifying role since the code executes in multiple accounts
      #It is created automatically with a logical ID of <function-logical-id>Role.
      # Events:
      #   getAZsAPI:
      #     Type: Api
      #     Properties:
      #       Path: /getazs
      #       Method: get
      # Environment:
      #   Variables:
      #     REGION: ap-southeast-2

  Lambda1:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: Lambda2
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./Lambda1/LambdaCode
      Description: 'Lambda function 1'
      MemorySize: 128
      Timeout: 30
      #Role: 'arn:aws:iam::453698135753:role/service-role/InfraTest'
      #Not specifying role since the code executes in multiple accounts
      #It is created automatically with a logical ID of <function-logical-id>Role.
      # Events:
      #   getAZsAPI:
      #     Type: Api
      #     Properties:
      #       Path: /getazs
      #       Method: get
      # Environment:
      #   Variables:
      #     REGION: ap-southeast-2

  Lambda2:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: Lambda1
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./Lambda2/LambdaCode
      Description: 'Lambda function 2'
      MemorySize: 128
      Timeout: 30
      #Role: 'arn:aws:iam::453698135753:role/service-role/InfraTest'
      #Not specifying role since the code executes in multiple accounts
      #It is created automatically with a logical ID of <function-logical-id>Role.
      # Events:
      #   getAZsAPI:
      #     Type: Api
      #     Properties:
      #       Path: /getazs
      #       Method: get
      # Environment:
      #   Variables:
      #     REGION: ap-southeast-2