AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Lambdas


Parameters:
  CDFURL:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: "CDFURL"
    Description: "CDF url for the lambda"


Resources:
  ProcessModemData:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: Process-Modem-Data
      Handler: process-modem-data.lambda_handler
      Runtime: python3.8
      CodeUri: ./process-modem-data/lambda-code
      Description: 'Process-Modem-Data'
      MemorySize: 128
      Timeout: 30
      Policies:
      - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          CDF_URL: !Ref CDFURL
          # CDF Contractor URL


  CreateRTRADIOMsg:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: Create-RTRADIO-Msg
      Handler: create-RTRADIO-msg.lambda_handler
      Runtime: python3.8
      CodeUri: ./create-RTRADIO-msg/lambda-code
      Description: 'Create-RTRADIO-Msg'
      MemorySize: 128
      Timeout: 30
      Policies:
      - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          CDF_URL: !Ref CDFURL
          # CDF Contractor URL

# Not specifying role because the scope of permissions is not known as of now.
# It is created automatically with a logical ID of <function-logical-id>Role with basic execution permissions.


  Lambda1:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: Lambda2
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./Lambda1/LambdaCode
      Description: 'Lambda function 1'
      MemorySize: 128
      Timeout: 30


  Lambda2:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: Lambda1
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./Lambda2/LambdaCode
      Description: 'Lambda function 2'
      MemorySize: 128
      Timeout: 30